pub const AGENTGATEWAY_VERSION: &str = "v1.4.1";
pub const AGENTGATEWAY_SHA256: &str =
    "7fcdc2a51cb7ab7f5c4b5a21f9066b3704f30ec6895c386332871381fab84ab6";

#[derive(Clone, Copy, Debug)]
pub struct GatewayPorts {
    pub interactive: u16,
    pub enrichment: u16,
    pub admin: u16,
}

fn render_lane_config(
    port: u16,
    admin_address: &str,
    requests: u64,
    request_interval: &str,
    tokens: u64,
    token_interval: &str,
) -> String {
    format!(
        r#"# Generated by Lumen. Do not place credentials in this file.
# yaml-language-server: $schema=https://agentgateway.dev/schema/config
config:
  enableIpv6: false
  adminAddr: {admin_address}
  statsAddr: off
  readinessAddr: off
llm:
  port: {port}
  policies:
    apiKey:
      mode: strict
      keys:
      - key: "$LUMEN_GATEWAY_BEARER"
    localRateLimit:
    - maxTokens: {requests}
      tokensPerFill: {requests}
      fillInterval: {request_interval}
      type: requests
    - maxTokens: {tokens}
      tokensPerFill: {tokens}
      fillInterval: {token_interval}
      type: tokens
  models:
  - name: lumen.answer.local
    provider: openAI
    params:
      model: qwen3.5:4b
      baseUrl: "$LUMEN_LOCAL_BASE_URL"
      apiKey: "$LUMEN_LOCAL_API_KEY"
      tokenize: true
    overrides:
      max_output_tokens: 1200
  - name: lumen.answer.cloud
    provider: openAI
    params:
      model: gpt-5-mini
      apiKey: "$LUMEN_OPENAI_API_KEY"
      tokenize: true
    overrides:
      max_output_tokens: 1200
  - name: lumen.embed.local
    provider: openAI
    params:
      model: embed-gemma:300m
      baseUrl: "$LUMEN_LOCAL_BASE_URL"
      apiKey: "$LUMEN_LOCAL_API_KEY"
      tokenize: true
  - name: lumen.embed.cloud
    provider: openAI
    params:
      model: text-embedding-3-small
      apiKey: "$LUMEN_OPENAI_API_KEY"
      tokenize: true
  - name: lumen.vision.cloud
    provider: openAI
    params:
      model: gpt-5-mini
      apiKey: "$LUMEN_OPENAI_API_KEY"
      tokenize: true
  - name: lumen.audio.cloud
    provider: openAI
    params:
      model: gpt-4o-mini-transcribe
      apiKey: "$LUMEN_OPENAI_API_KEY"
      tokenize: true
  - name: lumen.rerank.cloud
    provider: openAI
    params:
      model: gpt-5-mini
      apiKey: "$LUMEN_OPENAI_API_KEY"
      tokenize: true
"#,
    )
}

pub fn render_gateway_config(ports: GatewayPorts) -> String {
    render_lane_config(
        ports.interactive,
        &format!("127.0.0.1:{}", ports.admin),
        60,
        "1m",
        100_000,
        "1h",
    )
}

pub fn render_enrichment_config(ports: GatewayPorts) -> String {
    render_lane_config(ports.enrichment, "off", 10, "1m", 500_000, "24h")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::{fs, process::Command};

    #[test]
    fn config_has_all_aliases_separate_budgets_and_no_secret_values() {
        let ports = GatewayPorts {
            interactive: 41001,
            enrichment: 41002,
            admin: 41003,
        };
        let yaml = format!(
            "{}\n{}",
            render_gateway_config(ports),
            render_enrichment_config(ports)
        );
        for alias in [
            "lumen.answer.local",
            "lumen.answer.cloud",
            "lumen.embed.local",
            "lumen.embed.cloud",
            "lumen.vision.cloud",
            "lumen.audio.cloud",
            "lumen.rerank.cloud",
        ] {
            assert!(yaml.contains(alias));
        }
        assert!(yaml.contains("maxTokens: 60"));
        assert!(yaml.contains("maxTokens: 100000"));
        assert!(yaml.contains("maxTokens: 10"));
        assert!(yaml.contains("maxTokens: 500000"));
        assert!(yaml.contains("$LUMEN_OPENAI_API_KEY"));
        assert!(!yaml.contains("sk-test-secret"));
    }

    #[test]
    #[ignore = "requires the checksum-pinned AgentGateway sidecar"]
    fn pinned_binary_accepts_generated_config() {
        let binary = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("binaries/agentgateway-x86_64-pc-windows-msvc.exe");
        assert!(binary.is_file(), "run `bun run stage:sidecars` first");
        let directory = std::env::temp_dir().join(format!("lumen-agw-{}", uuid::Uuid::new_v4()));
        fs::create_dir_all(&directory).unwrap();
        let path = directory.join("config.yaml");
        fs::write(
            &path,
            render_gateway_config(GatewayPorts {
                interactive: 40101,
                enrichment: 40102,
                admin: 40103,
            }),
        )
        .unwrap();
        let output = Command::new(binary)
            .args(["-f", path.to_str().unwrap(), "--validate-only"])
            .env("LUMEN_GATEWAY_BEARER", "integration-test-token")
            .env("LUMEN_OPENAI_API_KEY", "integration-test-cloud")
            .env("LUMEN_LOCAL_BASE_URL", "http://127.0.0.1:11434/v1")
            .env("LUMEN_LOCAL_API_KEY", "integration-test-local")
            .output()
            .unwrap();
        let _ = fs::remove_dir_all(directory);
        assert!(
            output.status.success(),
            "stdout: {}\nstderr: {}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
}
