use super::registry::{AppliedRoute, ModelCapability, ProviderId};

pub const AGENTGATEWAY_VERSION: &str = "v1.4.1";
pub const AGENTGATEWAY_SHA256: &str =
    "7fcdc2a51cb7ab7f5c4b5a21f9066b3704f30ec6895c386332871381fab84ab6";

#[derive(Clone, Copy, Debug)]
pub struct GatewayPorts {
    pub interactive: u16,
    pub enrichment: u16,
    pub admin: u16,
}

fn quoted(value: &str) -> String {
    serde_json::to_string(value).unwrap_or_else(|_| "\"invalid\"".to_owned())
}

fn upstream_model(route: &AppliedRoute) -> &str {
    route.upstream_model()
}

fn custom_format(capability: ModelCapability) -> &'static str {
    match capability {
        ModelCapability::Embedding => "embeddings",
        ModelCapability::Rerank => "rerank",
        ModelCapability::Answer | ModelCapability::Vision | ModelCapability::Audio => "completions",
    }
}

fn render_model(route: &AppliedRoute) -> String {
    let alias = quoted(&route.alias);
    let model = quoted(upstream_model(route));
    let provider = match route.provider_id {
        ProviderId::Local | ProviderId::Openai => "    provider: openAI\n".to_owned(),
        ProviderId::Anthropic => "    provider: anthropic\n".to_owned(),
        ProviderId::Google => "    provider: gemini\n".to_owned(),
        ProviderId::OpenaiCompatible => format!(
            "    provider:\n      custom:\n        formats:\n        - type: {}\n",
            custom_format(route.capability),
        ),
    };
    let api_key = match route.provider_id {
        ProviderId::Local => "$LUMEN_LOCAL_API_KEY",
        ProviderId::Openai => "$LUMEN_OPENAI_API_KEY",
        ProviderId::Anthropic => "$LUMEN_ANTHROPIC_API_KEY",
        ProviderId::Google => "$LUMEN_GOOGLE_API_KEY",
        ProviderId::OpenaiCompatible => "$LUMEN_OPENAI_COMPATIBLE_API_KEY",
    };
    let base_url = match route.provider_id {
        ProviderId::Local => Some("$LUMEN_LOCAL_BASE_URL"),
        ProviderId::OpenaiCompatible => route.base_url.as_deref(),
        _ => None,
    };
    let base_url = base_url
        .map(|value| format!("      baseUrl: {}\n", quoted(value)))
        .unwrap_or_default();
    let max_output = matches!(
        route.capability,
        ModelCapability::Answer | ModelCapability::Vision
    )
    .then(|| "    overrides:\n      max_output_tokens: 1200\n")
    .unwrap_or_default();
    format!(
        "  - name: {alias}\n{provider}    params:\n      model: {model}\n{base_url}      apiKey: {api_key}\n      tokenize: true\n{max_output}"
    )
}

fn render_lane_config(
    port: u16,
    admin_address: &str,
    requests: u64,
    request_interval: &str,
    tokens: u64,
    token_interval: &str,
    routes: &[AppliedRoute],
) -> String {
    let models = routes.iter().map(render_model).collect::<Vec<_>>().join("");
    format!(
        r#"# Generated by Lumen. Do not place credentials in this file.
# yaml-language-server: $schema=https://agentgateway.dev/schema/config
config:
  enableIpv6: false
  adminAddr: {admin_address}
  statsAddr: off
  readinessAddr: off
llm:
  port: {port}
  policies:
    apiKey:
      mode: strict
      keys:
      - key: "$LUMEN_GATEWAY_BEARER"
    localRateLimit:
    - maxTokens: {requests}
      tokensPerFill: {requests}
      fillInterval: {request_interval}
      type: requests
    - maxTokens: {tokens}
      tokensPerFill: {tokens}
      fillInterval: {token_interval}
      type: tokens
  models:
{models}"#,
    )
}

pub fn render_gateway_config(ports: GatewayPorts, routes: &[AppliedRoute]) -> String {
    render_lane_config(
        ports.interactive,
        &format!("127.0.0.1:{}", ports.admin),
        60,
        "1m",
        100_000,
        "1h",
        routes,
    )
}

pub fn render_enrichment_config(ports: GatewayPorts, routes: &[AppliedRoute]) -> String {
    render_lane_config(ports.enrichment, "off", 10, "1m", 500_000, "24h", routes)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::gateway::registry::ProviderRegistry;
    use std::{fs, process::Command};

    fn routes() -> Vec<AppliedRoute> {
        ProviderRegistry::in_memory().routes()
    }

    #[test]
    fn config_has_all_aliases_separate_budgets_and_no_secret_values() {
        let ports = GatewayPorts {
            interactive: 41001,
            enrichment: 41002,
            admin: 41003,
        };
        let routes = routes();
        let yaml = format!(
            "{}\n{}",
            render_gateway_config(ports, &routes),
            render_enrichment_config(ports, &routes)
        );
        for alias in [
            "lumen.answer.local",
            "lumen.answer.cloud",
            "lumen.embed.local",
            "lumen.embed.cloud",
            "lumen.vision.cloud",
            "lumen.audio.cloud",
            "lumen.rerank.cloud",
        ] {
            assert!(yaml.contains(alias));
        }
        assert!(yaml.contains("maxTokens: 60"));
        assert!(yaml.contains("maxTokens: 100000"));
        assert!(yaml.contains("maxTokens: 10"));
        assert!(yaml.contains("maxTokens: 500000"));
        assert!(yaml.contains("$LUMEN_OPENAI_API_KEY"));
        assert!(!yaml.contains("sk-test-secret"));
    }

    #[test]
    fn custom_and_native_provider_syntax_is_generated_from_validated_routes() {
        let mut routes = routes();
        routes[1] = AppliedRoute {
            alias: "lumen.answer.cloud".to_owned(),
            capability: ModelCapability::Answer,
            provider_id: ProviderId::OpenaiCompatible,
            model_id: "openai-compatible:custom".to_owned(),
            base_url: Some("https://api.example.com/v1".to_owned()),
            upstream_model: Some("answer-model".to_owned()),
        };
        routes[4].provider_id = ProviderId::Google;
        routes[4].model_id = "google:gemini-2.5-flash".to_owned();
        let yaml = render_gateway_config(
            GatewayPorts {
                interactive: 1,
                enrichment: 2,
                admin: 3,
            },
            &routes,
        );
        assert!(yaml.contains("custom:\n        formats:\n        - type: completions"));
        assert!(yaml.contains("baseUrl: \"https://api.example.com/v1\""));
        assert!(yaml.contains("provider: gemini"));
    }

    #[test]
    #[ignore = "requires the checksum-pinned AgentGateway sidecar"]
    fn pinned_binary_accepts_generated_config() {
        let binary = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("binaries/agentgateway-x86_64-pc-windows-msvc.exe");
        assert!(binary.is_file(), "run `bun run stage:sidecars` first");
        let directory = std::env::temp_dir().join(format!("lumen-agw-{}", uuid::Uuid::new_v4()));
        fs::create_dir_all(&directory).unwrap();
        let path = directory.join("config.yaml");
        fs::write(
            &path,
            render_gateway_config(
                GatewayPorts {
                    interactive: 40101,
                    enrichment: 40102,
                    admin: 40103,
                },
                &routes(),
            ),
        )
        .unwrap();
        let output = Command::new(binary)
            .args(["-f", path.to_str().unwrap(), "--validate-only"])
            .env("LUMEN_GATEWAY_BEARER", "integration-test-token")
            .env("LUMEN_OPENAI_API_KEY", "integration-test-cloud")
            .env("LUMEN_LOCAL_BASE_URL", "http://127.0.0.1:11434/v1")
            .env("LUMEN_LOCAL_API_KEY", "integration-test-local")
            .output()
            .unwrap();
        let _ = fs::remove_dir_all(directory);
        assert!(
            output.status.success(),
            "stdout: {}\nstderr: {}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
}
